name: FactionAddon
version: '1.0'
main: com.minegolem.factionAddon.FactionAddon
api-version: '1.21'
authors: [ WorkWolf_2 ]
commands:
  showitem:
    description: show Chat item
  showinv:
    description: show chat Inv
  factionaddonreload:
    description: reload configs

